# ═══════════════════════════════════════════════════════════════
#   БИБЛИОТЕКА ОТВЕТОВ ШАРА
#   Добавляй новые ответы в любой раздел — просто копируй формат
#   После изменений перезапусти бота
# ═══════════════════════════════════════════════════════════════


# ── ПРИВЕТСТВИЯ ───────────────────────────────────────────────

GREETINGS = [
    "привет", "хай", "хей", "здравствуй", "здравствуйте",
    "здорово", "здарова", "приветик", "ку", "йоу", "дарова",
    "hello", "hi", "hey", "hiya", "howdy",
]

GREETING_ANSWERS_RU = [
    "Шар слышит тебя. Задай вопрос.",
    "Я здесь. Что ты хочешь узнать?",
    "Звёзды готовы. Спрашивай.",
    "Туман рассеивается. Задай вопрос.",
    "Мерлин слушает. Говори.",
    "Сферы сошлись. Спрашивай.",
    "Ты пришёл не случайно. Задай вопрос.",
    # ← добавляй сюда
]

GREETING_ANSWERS_EN = [
    "The Ball hears you. Ask your question.",
    "I am here. What do you wish to know?",
    "The stars are ready. Ask.",
    "The fog is lifting. Speak your question.",
    "Merlin listens. Speak.",
    "The spheres have aligned. Ask.",
    "You did not come here by chance. Ask.",
    # ← add here
]


# ══════════════════════════════════════════════════════════════
# ТРИГГЕРЫ ПОДДЕРЖКИ
# Если вопрос содержит одно из этих слов — шар отвечает цитатой
# ══════════════════════════════════════════════════════════════

COMFORT_TRIGGERS_RU = [
    "плохо", "грустно", "грустн", "тяжело", "больно",
    "устал", "одиноко", "одинок", "тревожно", "тревог",
    "страшно", "не могу", "всё плохо", "тоскливо", "тоск",
    "депрессия", "паника", "пусто", "темно", "несчастн",
    "нелегко", "беспокойно", "беспокой", "болит", "болью",
    "плачу", "плакать", "слёзы", "слезы", "безнадёжно",
    "бессмысленно", "устала", "сложно", "непросто",
]

COMFORT_TRIGGERS_EN = [
    "sad", "awful", "lonely", "anxious", "scared",
    "depressed", "hurts", "hurting", "empty",
    "terrible", "horrible", "miserable", "broken", "hopeless",
    "worried", "afraid", "numb", "struggling",
    "overwhelmed", "exhausted", "stressed", "crying",
    "tears", "hopeless", "meaningless", "lost", "pain",
    "tired of", "can't anymore", "feeling bad", "feeling low",
]


# ══════════════════════════════════════════════════════════════
# ЦИТАТЫ ПОДДЕРЖКИ
# Появляются когда в вопросе чувствуется боль или тяжесть
# ══════════════════════════════════════════════════════════════

COMFORT_RU = [
    "Туман не вечен.",
    "Даже звёзды появляются только ночью.",
    "Иногда отдых — тоже путь.",
    "Не все ответы приходят сразу.",
    "Ты уже ближе, чем тебе кажется.",
    "Шаг за шагом — тоже магия.",
    "Некоторые вещи расцветают медленно.",
    "Сегодня достаточно просто дышать.",
    "Даже тихое пламя способно пережить бурю.",
    "Твоя история ещё не закончена.",
    "Иногда миру нужно время, чтобы ответить.",
    "Не каждый потерянный путь ведёт не туда.",
    "Сомнения не делают тебя слабым.",
    "Иногда сердце знает раньше разума.",
    "Ты не обязан нести всё один.",
    "Даже луна исчезает, чтобы вернуться.",
    "Усталость — не поражение.",
    "Иногда самое важное происходит незаметно.",
    "Ты можешь остановиться. Мир не рухнет.",
    "Свет не всегда бывает громким.",
    "Некоторые двери открываются только в тишине.",
    "Мягкость — тоже сила.",
    "Не торопи свою весну.",
    "Даже после долгой ночи приходит утро.",
    "Ты имеешь право начать заново.",
    "Иногда ответ — просто пережить этот день.",
    "То, что сейчас трудно, не будет вечным.",
    "Береги себя так, как берёг бы кого-то любимого.",
    "Небо не требует от тебя совершенства.",
    "Даже маленький шаг меняет путь.",
    "Не всякая пауза означает конец.",
    "Иногда нужно потеряться, чтобы найти новый путь.",
    "Тишина тоже умеет лечить.",
    "Даже разбитые вещи отражают свет.",
    "Ты не обязан цвести каждый день.",
    "Иногда сердце устаёт раньше тела.",
    "Ночь не спрашивает, готов ли ты к рассвету.",
    "Некоторые ответы приходят только в покое.",
    "То, что кажется концом, может быть поворотом.",
    "Даже дождь не идёт вечно.",
    "Ты уже пережил дни, которых боялся.",
    "Не каждый шаг должен быть уверенным.",
    "Сила не всегда выглядит как борьба.",
    "Иногда достаточно просто остаться.",
    "Внутри тебя больше света, чем ты думаешь.",
    "Некоторые дороги становятся яснее только в пути.",
    "Твоя ценность не зависит от твоей продуктивности.",
    "Мир не требует от тебя быть железным.",
    "Даже медленное движение — всё ещё движение.",
    "Иногда душе нужно больше времени.",
    "Не бойся начинать заново.",
    "Даже самые глубокие воды однажды становятся спокойнее.",
    "Тепло возвращается постепенно.",
    "Иногда жизнь просит не скорости, а терпения.",
    "Ты не обязан знать всё наперёд.",
    "Некоторые перемены приходят тихо.",
    "Свет остаётся, даже когда его не видно.",
    "Ты можешь быть уставшим и всё ещё сильным.",
    "Позволь себе идти медленно.",
    "Даже звёзды не спешат.",
    "Иногда лучший ответ — дать себе время.",
    "Шар чувствует: ты слишком строг к себе.",
    "Не все битвы нужно выигрывать сегодня.",
    "Есть дни для роста. Есть дни для тишины.",
    "Даже маленькая надежда способна пережить ночь.",
    "Ты не обязан быть понятным всем.",
    "Некоторые раны заживают незаметно.",
    "Иногда путь меняется прямо под ногами.",
    "Ты всё ещё здесь. Это уже немало.",
    "Не позволяй одному тяжёлому дню стать всей историей.",
    "Иногда нужно отпустить вопрос, чтобы услышать ответ.",
    "Даже у луны бывают тёмные фазы.",
    "Твоя мягкость — не слабость.",
    "Некоторые чувства нельзя исправить — только прожить.",
    "Ты не опоздал к своей жизни.",
    "Иногда магия — это просто продолжать.",
    "Не все штормы приходят, чтобы разрушить.",
    "Ты имеешь право на передышку.",
    "Даже если сейчас ничего не ясно — путь всё ещё существует.",
    "Твоё сердце знает больше, чем страх.",
    "Иногда туман приходит, чтобы замедлить тебя, а не сбить с пути.",
    "Ты не обязан нести прошлое дальше.",
    "Даже тихие люди способны менять мир.",
    "Некоторые ответы приходят после сна.",
    "Не каждый день должен быть великим.",
    "Шар видит: ты держишься лучше, чем думаешь.",
    "Иногда важно не победить, а сохранить себя.",
    "Всё живое проходит через зиму.",
    "Ты можешь быть растерянным и всё ещё двигаться вперёд.",
    "Некоторые вещи становятся легче не сразу.",
    "Даже потухший костёр хранит тепло.",
    "Мир становится мягче, когда ты перестаёшь воевать с собой.",
    "Не бойся неизвестности. В ней тоже есть жизнь.",
    "Иногда самое мудрое — ничего не торопить.",
    "Твоё будущее не решено одним плохим днём.",
    "Даже медленно текущая река достигает моря.",
    "Свет возвращается маленькими шагами.",
    "Шар шепчет: ты справишься.",
    "Иногда выжить — уже подвиг.",
    "Некоторые чудеса приходят тихо.",
    "Вам не нужно видеть всю лестницу — просто шагните на первую ступеньку.",
    "Ты не обязан быть в порядке прямо сейчас.",
    "Иногда самый смелый поступок — просто продолжать.",
    "Ты уже прошёл через всё, что казалось невозможным.",
    "Позволь себе чувствовать. Это и есть быть живым.",
    "Каждое утро — это шанс начать заново. Даже если вчера было тяжело.",
    "Делай что можешь, с тем что имеешь, там где ты есть.",
    "Твоя боль сейчас — не навсегда. Только сейчас.",
    "Твоё сердце знает путь раньше разума.",
    # ── цитаты с именами ──
    "Всё проходит. Пройдёт и это.\n— Царь Соломон",
    "Даже самая тёмная ночь заканчивается рассветом.\n— Виктор Гюго",
    "Мужество — это продолжать, даже когда страшно.\n— Теодор Рузвельт",
    "Тот, кто имеет зачем жить, выдержит почти любое как.\n— Фридрих Ницше",
    "Не спеши. Всё приходит вовремя.\n— Лао-цзы",
    "Нельзя пересечь море, всё время глядя на берег.\n— Рабиндранат Тагор",
    "Среди зимы я понял, что во мне есть непобедимое лето.\n— Альбер Камю",
    "Даже дорога в тысячу ли начинается с первого шага.\n— Лао-цзы",
    "Будь мягок. Мир и так полон острых углов.\n— Неизвестный",
    "Иногда выжить — уже победа.\n— Неизвестный",
    "Надежда — это умение слышать музыку будущего.\n— Питер Кузмич",
    "Тишина тоже является ответом.\n— Восточная мудрость",
    "Пока ты жив — всё возможно.\n— Марк Аврелий",
    "Раны — место, через которое в нас входит свет.\n— Руми",
    "Терпение — горькое растение, но сладкий плод.\n— Жан-Жак Руссо",
    "Луна не боится темноты.\n— Неизвестный",
    "Иногда отдых — самая мудрая форма движения.\n— Неизвестный",
    "Спокойное сердце видит дальше.\n— Восточная мудрость",
    "Даже сломанные часы дважды в день показывают верное время.\n— Народная мудрость",
    # ← добавляй сюда
]

COMFORT_EN = [
    "Fog is not forever.",
    "Even stars only appear at night.",
    "Sometimes rest is also the way.",
    "Not all answers come at once.",
    "You are already closer than you think.",
    "Step by step is also magic.",
    "Some things bloom slowly.",
    "Today, breathing is enough.",
    "Even a quiet flame can survive a storm.",
    "Your story is not over yet.",
    "Sometimes the world needs time to answer.",
    "Not every lost path leads the wrong way.",
    "Doubt does not make you weak.",
    "Sometimes the heart knows before the mind.",
    "You are not obliged to carry everything alone.",
    "Even the moon disappears — only to return.",
    "Fatigue is not defeat.",
    "Sometimes the most important things happen quietly.",
    "You can stop. The world will not fall apart.",
    "Light is not always loud.",
    "Some doors only open in stillness.",
    "Gentleness is also strength.",
    "Do not rush your spring.",
    "Even after a long night, morning comes.",
    "You have the right to begin again.",
    "Sometimes the answer is simply to survive this day.",
    "What is hard right now will not be forever.",
    "Take care of yourself the way you would care for someone you love.",
    "The sky does not demand perfection from you.",
    "Even a small step changes the path.",
    "Not every pause means an ending.",
    "Sometimes you need to get lost to find a new way.",
    "Silence also knows how to heal.",
    "Even broken things reflect light.",
    "You are not obliged to bloom every day.",
    "Sometimes the heart tires before the body.",
    "The night does not ask if you are ready for dawn.",
    "Some answers only come in stillness.",
    "What seems like an ending may be a turning point.",
    "Even the rain does not last forever.",
    "You have already survived the days you feared.",
    "Not every step needs to be certain.",
    "Strength does not always look like struggle.",
    "Sometimes it is enough to simply stay.",
    "There is more light inside you than you think.",
    "Some roads only become clear as you walk them.",
    "Your worth does not depend on your productivity.",
    "The world does not require you to be made of iron.",
    "Even slow movement is still movement.",
    "Sometimes the soul simply needs more time.",
    "Do not be afraid to start again.",
    "Even the deepest waters grow calm in time.",
    "Warmth returns gradually.",
    "Sometimes life asks for patience, not speed.",
    "You do not have to know everything in advance.",
    "Some changes arrive quietly.",
    "The light remains even when it cannot be seen.",
    "You can be tired and still be strong.",
    "Allow yourself to go slowly.",
    "Even stars do not rush.",
    "Sometimes the best answer is to give yourself time.",
    "The ball senses: you are too hard on yourself.",
    "Not every battle needs to be won today.",
    "There are days for growing. There are days for stillness.",
    "Even a small hope can survive the night.",
    "You are not obliged to be understood by everyone.",
    "Some wounds heal quietly.",
    "Sometimes the path shifts beneath your feet.",
    "You are still here. That is already something.",
    "Do not let one heavy day become your whole story.",
    "Sometimes you need to release the question to hear the answer.",
    "Even the moon has dark phases.",
    "Your gentleness is not weakness.",
    "Some feelings cannot be fixed — only lived through.",
    "You have not arrived late to your own life.",
    "Sometimes magic is simply continuing.",
    "Not every storm comes to destroy.",
    "You have the right to rest.",
    "Even when nothing is clear right now — the path still exists.",
    "Your heart knows more than your fear.",
    "Sometimes the fog comes to slow you down, not lead you astray.",
    "You are not obliged to carry the past any further.",
    "Even quiet people can change the world.",
    "Some answers come after sleep.",
    "Not every day needs to be great.",
    "The ball sees: you are holding on better than you think.",
    "Sometimes what matters is not to win, but to preserve yourself.",
    "Everything alive passes through winter.",
    "You can be lost and still move forward.",
    "Some things get easier — just not right away.",
    "Even a burnt-out fire holds warmth.",
    "The world grows softer when you stop fighting yourself.",
    "Do not fear the unknown. Life lives there too.",
    "Sometimes the wisest thing is to let nothing be rushed.",
    "Your future is not decided by one bad day.",
    "Even a slow-moving river reaches the sea.",
    "Light returns in small steps.",
    "The ball whispers: you will get through this.",
    "Sometimes just surviving is already an act of courage.",
    "Some miracles arrive quietly.",
    "You don't have to see the whole staircase — just take the first step.",
    "You don't have to be okay right now.",
    "Sometimes the bravest thing is simply to continue.",
    "You have already been through everything that seemed impossible.",
    "Allow yourself to feel. That is what it means to be alive.",
    "Every morning is a chance to begin again. Even after a hard day.",
    "Do what you can, with what you have, where you are.",
    "This pain is not forever. Only for now.",
    "Your heart knows the way before the mind does.",
    # ── named quotes ──
    "This too shall pass.\n— King Solomon",
    "Even the darkest night will end and the sun will rise.\n— Victor Hugo",
    "Courage is going on even when you are afraid.\n— Theodore Roosevelt",
    "He who has a why to live can bear almost any how.\n— Friedrich Nietzsche",
    "Nature does not hurry, yet everything is accomplished.\n— Lao Tzu",
    "You can't cross the sea merely by standing and staring at the water.\n— Rabindranath Tagore",
    "In the midst of winter, I found there was within me an invincible summer.\n— Albert Camus",
    "A journey of a thousand miles begins with a single step.\n— Lao Tzu",
    "Be gentle. The world already has too many sharp edges.\n— Unknown",
    "Sometimes surviving is already a victory.\n— Unknown",
    "Hope is hearing the music of the future.\n— Peter Kuzmic",
    "Silence is also an answer.\n— Eastern wisdom",
    "While you live, anything is possible.\n— Marcus Aurelius",
    "The wound is the place where the Light enters you.\n— Rumi",
    "Patience is bitter, but its fruit is sweet.\n— Jean-Jacques Rousseau",
    "The moon is not afraid of darkness.\n— Unknown",
    "Sometimes rest is the wisest form of movement.\n— Unknown",
    "A calm heart sees further.\n— Eastern wisdom",
    "Even a broken clock is right twice a day.\n— Folk wisdom",
    # ← add here
]


# ══════════════════════════════════════════════════════════════
# УРОВЕНЬ 1 — "ШАР"
# Первые 20 вопросов. Очень коротко. Как классический магический шар.
# Одна фраза, максимум 5 слов.
# ══════════════════════════════════════════════════════════════

SIMPLE_RU = [
    "Да.",
    "Нет.",
    "Определённо да.",
    "Определённо нет.",
    "Вероятно.",
    "Сомнительно.",
    "Спроси позже.",
    "Не сейчас.",
    "Туманно.",
    "Знаки неясны.",
    "Звёзды молчат.",
    "Исход скрыт.",
    "Предрешено.",
    "Всё возможно.",
    "Время покажет.",
    "Не исключено.",
    "Маловероятно.",
    "Скорее да.",
    "Скорее нет.",
    "Знаки говорят да.",
    "Знаки против.",
    "Можешь рассчитывать.",
    "Не рассчитывай.",
    "Всё может быть.",
    "Ты с этим справишься.",
    "Безусловно.",
    "У тебя ещё есть сомнения?",
    "Естественно.",
    "Тебе оно надо?",
    "Тебе это не надо.",
    "ДА.",
    # ← добавляй сюда
]

SIMPLE_EN = [
    "Yes.",
    "No.",
    "Certainly yes.",
    "Certainly not.",
    "Likely.",
    "Doubtful.",
    "Ask later.",
    "Not now.",
    "Unclear.",
    "Signs are silent.",
    "The stars are quiet.",
    "The outcome is hidden.",
    "It is decided.",
    "All is possible.",
    "Time will tell.",
    "Cannot be ruled out.",
    "Unlikely.",
    "Most likely yes.",
    "Most likely no.",
    "Signs say yes.",
    "Signs say no.",
    "Count on it.",
    "Don't count on it.",
    "Anything is possible.",
    "You can handle this.",
    "Absolutely.",
    "Do you still have doubts?",
    "Naturally.",
    "Do you really need it?",
    "You don't need this.",
    # ← add here
]


# ══════════════════════════════════════════════════════════════
# УРОВЕНЬ 2 — "ОРАКУЛ"
# Вопросы 20–99. Ответ + короткая мистическая фраза.
# Формат: "Да. Но путь будет долгим."
# ══════════════════════════════════════════════════════════════

ORACLE_RU = [
    "Да. Но путь будет долгим.",
    "Нет. Звёзды против этого.",
    "Да. Хотя цена окажется выше, чем ты думаешь.",
    "Нет. Не сейчас — и не с этим.",
    "Да. Но не так, как ты представляешь.",
    "Туманно. Подожди новолуния.",
    "Вероятно. Если решишься вовремя.",
    "Исход скрыт. Даже от меня.",
    "Нет. Другое ждёт тебя впереди.",
    "Да. И ты уже знаешь это.",
    "Нет. Это не твоя дорога.",
    "Спроси позже. Силы ещё не сошлись.",
    "Вероятно. Но не без усилий.",
    "Да. Страх — единственное препятствие.",
    "Нет. Но это избавит тебя от большего.",
    "Да. Первый шаг уже сделан.",
    "Сомнительно. Проверь намерение.",
    "Нет. Время этого ещё не пришло.",
    "Да. Но сначала — потеря.",
    "Туманно. Слушай тишину.",
    "Знаки молчат. Это тоже ответ.",
    "Да. Только не медли.",
    "Нет. Что-то важное ещё не случилось.",
    "Вероятно. Звёзды склоняются к этому.",
    "Да. Доверяй тому, что чувствуешь.",
    "Нет. Твоя интуиция права.",
    "Исход благоприятен. Действуй.",
    "Да. Но не в одиночку.",
    "Нет. Отпусти — и станет легче.",
    "Туманно. Этот вопрос требует времени.",
    "Да. Скоро потеплеет — во всех смыслах.",
    "Нет. Но осень принесёт кое-что лучше.",
    "Туманно. Как утро у реки.",
    "Вероятно. Смотри на небо сегодня.",
    # ← добавляй сюда
]

ORACLE_EN = [
    "Yes. But the path will be long.",
    "No. The stars oppose it.",
    "Yes. Though the price will be higher than you think.",
    "No. Not now — not with this.",
    "Yes. But not as you imagine.",
    "Unclear. Wait for the new moon.",
    "Likely. If you act in time.",
    "The outcome is hidden. Even from me.",
    "No. Something else awaits you ahead.",
    "Yes. And you already know this.",
    "No. This is not your road.",
    "Ask later. The forces have not aligned.",
    "Likely. But not without effort.",
    "Yes. Fear is the only obstacle.",
    "No. But this will spare you something greater.",
    "Yes. The first step has already been taken.",
    "Doubtful. Examine your intention.",
    "No. Its time has not yet come.",
    "Yes. But first — a loss.",
    "Unclear. Listen to the silence.",
    "The signs are quiet. That is also an answer.",
    "Yes. Do not delay.",
    "No. Something important has not happened yet.",
    "Likely. The stars lean toward this.",
    "Yes. Trust what you feel.",
    "No. Your intuition is right.",
    "The outcome is favorable. Act.",
    "Yes. But not alone.",
    "No. Let go — and it will become easier.",
    "Unclear. This question needs time.",
    "Yes. Something is warming up — in every sense.",
    "No. But autumn will bring something better.",
    "Unclear. Like morning at the river.",
    "Likely. Watch the sky today.",
    # ← add here
]


# ══════════════════════════════════════════════════════════════
# УРОВЕНЬ 3 — "МЕРЛИН"
# 100+ вопросов. Глубже, личнее. Как будто шар уже знает тебя.
# 1–2 предложения. Может быть парадокс, неожиданный поворот.
# ══════════════════════════════════════════════════════════════

MERLIN_RU = [
    "Да. Ты давно знаешь ответ — просто искал разрешения.",
    "Нет. И глубоко внутри ты рад этому.",
    "Да. Но сначала придётся стать другим человеком.",
    "Нет. Этот путь ведёт не туда, куда ты думаешь.",
    "Да. Вселенная уже движется навстречу.",
    "Нет. То, чего ты боишься потерять, уже изменилось.",
    "Да. Но это потребует от тебя честности с собой.",
    "Туманно. Ты задаёшь не тот вопрос.",
    "Нет. Позволь этому уйти.",
    "Да. Именно сейчас — не позже.",
    "Нет. За этим желанием стоит другое, настоящее.",
    "Да. Ты сильнее, чем думаешь.",
    "Нет. Твоя усталость говорит громче вопроса.",
    "Да. Первый шаг — самый важный. Остальное придёт.",
    "Нет. Но отказ откроет другую дверь.",
    "Да. Доверяй процессу, даже когда не видишь пути.",
    "Туманно. Подожди, пока утихнет внутренний шум.",
    "Нет. Это чужое желание, не твоё.",
    "Да. Ты уже на правильном пути — просто не замечаешь.",
    "Нет. Иногда «нет» — это самый добрый ответ.",
    "Да. Страх, который ты чувствуешь — знак, что это важно.",
    "Нет. Береги энергию для того, что действительно твоё.",
    "Да. Но результат удивит тебя.",
    "Нет. Вернись к этому вопросу через месяц.",
    "Да. Отпусти контроль — и всё встанет на место.",
    "Нет. Ты заслуживаешь большего, чем просишь.",
    "Да. Люди вокруг видят в тебе больше, чем ты сам.",
    "Туманно. Реши сначала, чего ты на самом деле хочешь.",
    "Нет. Это испытание, а не приговор.",
    "Да. Время пришло.",
    "Лето обещает быть ослепительным. Ты готов?",
    "Что-то тёплое уже движется в твою сторону.",
    "Небо сегодня — твой главный советчик.",
    "Цвет твоего настроения сейчас — предзакатный.",
    "Пахнет переменами. Хорошими.",
    "Этот вопрос просит дождя и открытого окна.",
    "Погода внутри тебя сейчас важнее, чем снаружи.",
    "Что-то распускается. Внутри или снаружи — неважно.",
    "Твоё лето начнётся чуть позже, но будет ярче.",
    "Всё живое сейчас тянется к свету. И ты тоже.",
    "Сейчас золотой час. Не трать его на сомнения.",
    "Позволь себе побыть облаком.",
    "Что-то цветёт там, куда ты пока не смотришь.",
    # ← добавляй сюда
]

MERLIN_EN = [
    "Yes. You have long known the answer — you were just seeking permission.",
    "No. And deep inside, you are glad.",
    "Yes. But first you will need to become a different person.",
    "No. This path leads somewhere other than you think.",
    "Yes. The universe is already moving toward you.",
    "No. What you fear losing has already changed.",
    "Yes. But it will require honesty with yourself.",
    "Unclear. You are asking the wrong question.",
    "No. Let this go.",
    "Yes. Right now — not later.",
    "No. Behind this wish is another, truer one.",
    "Yes. You are stronger than you believe.",
    "No. Your exhaustion speaks louder than the question.",
    "Yes. The first step is the most important. The rest will follow.",
    "No. But the refusal will open another door.",
    "Yes. Trust the process, even when you cannot see the path.",
    "Unclear. Wait until the inner noise settles.",
    "No. This is someone else's desire, not yours.",
    "Yes. You are already on the right path — you just don't see it.",
    "No. Sometimes 'no' is the kindest answer.",
    "Yes. The fear you feel is a sign that this matters.",
    "No. Save your energy for what is truly yours.",
    "Yes. But the result will surprise you.",
    "No. Return to this question in a month.",
    "Yes. Release control — and everything will fall into place.",
    "No. You deserve more than what you are asking for.",
    "Yes. The people around you see more in you than you do.",
    "Unclear. First decide what you truly want.",
    "No. This is a test, not a verdict.",
    "Yes. The time has come.",
    "Summer promises to be dazzling. Are you ready?",
    "Something warm is already moving your way.",
    "The color of your mood right now is pre-sunset.",
    "This question smells like rain and open windows.",
    "Your summer will start later, but shine brighter.",
    "Something is blooming — inside or outside, it doesn't matter.",
    "The weather inside you matters more than the forecast.",
    "Let yourself be a cloud for a while.",
    "Everything alive is reaching toward the light. So are you.",
    "This is the golden hour. Don't spend it on doubt.",
    "Something is flowering where you aren't looking yet.",
    # ← add here
]
